// Code generated by generate/config/gen.go; DO NOT EDIT.

package config

const GatekeeperTargetPort = 3333
const GatekeeperLivenessCheckHttpEnabled = false
const GatekeeperLivenessCheckHttpProbeIntervalSeconds = 1
const GatekeeperLivenessCheckLogEnabled = true
const GatekeeperLivenessCheckLogSearchString = "Server running at"

const SyscallsDelayEnforceUntilCheck = true
const SyscallsKillTargetIfNotAllowed = true

var SyscallsAllowList = map[string]bool{}
