package runtime

var syscallMap = map[string][]string{
	"File Read Operations": []string{
		"access",
		"close",
		"close_range",
		"faccessat",
		"faccessat2",
		"fadvise64",
		"fallocate",
		"fstat",
		"fstatat64",
		"fstatfs",
		"fstatfs64",
		"getdents",
		"getdents64",
		"llseek",
		"lseek",
		"lstat",
		"name_to_handle_at",
		"newfstatat",
		// "open", not tested
		"openat",
		"read",
		"readahead",
		"readlink",
		"readlinkat",
		"readv",
		"stat",
		"statfs",
		"statx",
	},
	"File Write Operations": []string{
		"creat",
		"copy_file_range",
		"ftruncate",
		"ftruncate64",
		"futimesat",
		"link",
		"linkat",
		"lremovexattr",
		"mkdir",
		"mkdirat",
		"mknod",
		"mknodat",
		"openat2", // moved to write operations due to lack of applications that can be used for testing
		"removexattr",
		"rename",
		"renameat",
		"renameat2",
		"rmdir",
		"sync_file_range",
		"symlink",
		"symlinkat",
		"truncate",
		"truncate64",
		"umask",
		"unlink",
		"unlinkat",
		"utime",
		"utimensat",
		"utimensat_time64",
		"utimes",
		"write",
		"writev",
	},
	"File Permissions": []string{
		"chmod",
		"chown",
		"fchmod",
		"fchmodat",
		"fchmodat2",
		"fchown",
		"fchownat",
	},
	"Process Management": []string{
		"arch_prctl",
		"clone3",
		"fork",
		"vfork",
		"execve",
		"execveat",
		"exit",
		"exit_group",
		"getpid",
		"getppid",
		"getpgid",
		"getpgrp",
		"gettid",
		"getsid",
		"getcwd",
		"fchdir",
		"kill",
		"pause",
		"prctl",
		"sched_getaffinity",
		"sched_getattr",
		"sched_getparam",
		"sched_get_priority_max",
		"sched_get_priority_min",
		"sched_getscheduler",
		"sched_rr_get_interval",
		"sched_setaffinity",
		"sched_setattr",
		"sched_setparam",
		"sched_setscheduler",
		"sched_yield",
		"setpgid",
		"setsid",
		"tgkill",
		"tkill",
		"wait4",
		"waitid",
		"waitpid",
		"pidfd_open",
		"pidfd_send_signal",
		"set_tid_address",
	},
	"Networking Client": []string{
		// "accept",
		// "accept4",
		"bind",
		"connect",
		"getpeername",
		"getsockname",
		"getsockopt",
		// "listen",
		"recv",
		"recvfrom",
		"recvmmsg",
		"recvmmsg_time64",
		"recvmsg",
		"send",
		"sendfile",
		"sendmmsg",
		"sendmsg",
		"sendto",
		"setsockopt",
		"shutdown",
		"socket",
		"socketpair",
		"inotify_add_watch",
		"inotify_init",
		"inotify_init1",
		"inotify_rm_watch",
		"write",
	},
	"Networking Server": []string{
		"accept",
		"accept4",
		"bind",
		// "connect",
		"getpeername",
		"getsockname",
		"getsockopt",
		"listen",
		// "recv",
		// "recvfrom",
		// "recvmmsg",
		// "recvmmsg_time64",
		// "recvmsg",
		// "send",
		// "sendfile",
		// "sendmmsg",
		// "sendmsg",
		// "sendto",
		"setsockopt",
		"shutdown",
		"socket",
		"socketpair",
		"inotify_add_watch",
		"inotify_init",
		"inotify_init1",
		"inotify_rm_watch",
		"write",
	},
	"File Descriptor Operations": []string{
		"dup",
		"dup2",
		"dup3",
		"epoll_create",
		"epoll_create1",
		"epoll_ctl",
		"epoll_pwait",
		"epoll_pwait2",
		"epoll_wait",
		"eventfd",
		"eventfd2",
		"fcntl",
		"poll",
		"ppoll",
		"ppoll_time64",
		"pselect6",
		"select",
		"signalfd",
		"signalfd4",
	},
	"Memory Management": []string{
		"brk",
		"madvise",
		"map_shadow_stack",
		"memfd_create",
		"memfd_secret",
		"mincore",
		"mlock",
		"mlock2",
		"mlockall",
		"mmap",
		"mprotect",
		"mremap",
		"msync",
		"munlock",
		"munlockall",
		"munmap",
		"remap_file_pages",
		"pkey_alloc",
		"pkey_free",
		"pkey_mprotect",
	},
	"Signals": []string{
		"rt_sigaction",
		"rt_sigpending",
		"rt_sigprocmask",
		"rt_sigqueueinfo",
		"rt_sigreturn",
		"rt_sigsuspend",
		"rt_sigtimedwait",
		"rt_sigtimedwait_time64",
		"rt_tgsigqueueinfo",
		"sigaltstack",
		"sigprocmask",
		"sigreturn",
	},
	"Timers and Clocks": []string{
		"adjtimex",
		"alarm",
		"clock_adjtime",
		"clock_getres",
		"clock_gettime",
		"clock_nanosleep",
		"getitimer",
		"gettimeofday",
		"nanosleep",
		"setitimer",
		"time",
		"timer_create",
		"timer_delete",
		"timer_getoverrun",
		"timer_gettime",
		"timer_settime",
		"timerfd_create",
		"timerfd_gettime",
		"timerfd_settime",
		"times",
	},
	"Security and Permissions": []string{
		"chdir",
		"capget",
		"capset",
		"getxattr",
		"fgetxattr",
		"lgetxattr",
		"setxattr",
		"fsetxattr",
		"lsetxattr",
		"removexattr",
		"fremovexattr",
		"chmod",
		"chown",
		"listxattr",
		"setuid",
		"setgid",
		"seteuid",
		"setegid",
		"setresuid",
		"setresgid",
		"setfsuid",
		"setfsgid",
		"setgroups",
		"getuid",
		"getgid",
		"geteuid",
		"getegid",
		"getgroups",
		"seccomp",
	},
	"System Information": []string{
		// "getcpu",
		"uname",
		"sysinfo",
		"getrlimit",
		// "setrlimit",
		"ugetrlimit",
	},
	"IPC": []string{
		"semctl",
		"semget",
		"semop",
		"semtimedop",
		"shmat",
		"shmctl",
		"shmdt",
		"shmget",
		"msgctl",
		"msgget",
		"msgrcv",
		"msgsnd",
		"mq_getsetattr",
		"mq_notify",
		"mq_open",
		"mq_timedreceive",
		"mq_timedsend",
		"mq_unlink",
	},
	"Synchronization": []string{
		"futex",
		"futex_wait",
		"futex_wake",
		"set_robust_list",
		"get_robust_list",
		"flock",
	},
	"Miscellaneous": []string{
		"landlock_add_rule",
		"landlock_create_ruleset",
		"landlock_restrict_self",
		"sync",
		"syncfs",
		"tee",
		"splice",
		"vmsplice",
		"process_mrelease",
		"rseq",
		"membarrier",
		"restart_syscall",
		"cachestat",
		"getrandom",
		"io_cancel",
		"ioctl",
		"io_destroy",
		"io_getevents",
		"ioprio_get",
		"ioprio_set",
		"io_setup",
		"io_submit",
		"pread64",
		"preadv",
		"prlimit64",
		"pwrite64",
		"pwritev",
		"pipe",
		"pipe2",
	},
}
