package runtime

// Groups below intentionally separate raw IO operations from metadata-changing operations.
// This allows granting write IO (write*, pwrite*, fallocate) without implicitly enabling
// file creation, renames, or unlinking unless desired. Tracer logic further gates intent.
var syscallMap = map[string][]string{
	// Conservative default: allow time queries and sleeping, but exclude
	// system clock adjustments and advanced timer facilities by default.
	"Basic Time": {
		"clock_gettime",
		"clock_getres",
		"gettimeofday",
		"time",
		"times",
		"nanosleep",
		"clock_nanosleep",
	},
	"File Read Operations": {
		"access",
		"faccessat",
		"faccessat2",
		"fadvise64",
		"fstat",
		"fstatfs",
		// Extended attribute reads (metadata-only)
		"getxattr",
		"fgetxattr",
		"lgetxattr",
		"listxattr",
		"flistxattr",
		"llistxattr",
		"getdents",
		"getdents64",
		"lseek",
		"lstat",
		"name_to_handle_at",
		"newfstatat",
		"pread64",
		"preadv",
		"readahead",
		"readlink",
		"readlinkat",
		"readv",
		"stat",
		"statfs",
		"statx",
	},
	// Raw IO write operations (data writes or allocation hints), separated from metadata ops.
	"File Write Operations": {
		"copy_file_range",
		"fallocate",
		"fdatasync",
		"fsync",
		"sync_file_range",
		"write",
		"writev",
		"pwrite64",
		"pwritev",
	},
	"File Open": {
		"open",
		"openat",
		"openat2",
	},
	// File creation and metadata-changing operations (ownership, links, renames, times, size).
	"File Create/Metadata": {
		"creat",
		"ftruncate",
		"truncate",
		"rename",
		"renameat",
		"renameat2",
		"link",
		"linkat",
		"mkdir",
		"mkdirat",
		"mknod",
		"mknodat",
		"symlink",
		"symlinkat",
		"umask",
		"unlink",
		"unlinkat",
		"utime",
		"utimensat",
		"utimensat_time64",
		"utimes",
		"futimesat",
	},
	"File Permissions": {
		"chmod",
		"chown",
		"fchmod",
		"fchmodat",
		"fchown",
		"fchownat",
	},
	"Process Management": {
		"arch_prctl",
		"alarm",
		"clone",
		"clone3",
		"fork",
		"vfork",
		"execve",
		"execveat",
		"exit",
		"exit_group",
		"getpid",
		"getppid",
		"getpgid",
		"getpgrp",
		"gettid",
		"getsid",
		"getcwd",
		"fchdir",
		"io_uring_enter",
		"io_uring_register",
		"io_uring_setup",
		"kill",
		"nanosleep",
		"pause",
		"prctl",
		"sched_getaffinity",
		"sched_getattr",
		"sched_getparam",
		"sched_get_priority_max",
		"sched_get_priority_min",
		"sched_getscheduler",
		"sched_rr_get_interval",
		"sched_setaffinity",
		"sched_setattr",
		"sched_setparam",
		"sched_setscheduler",
		"sched_yield",
		"setpgid",
		"setsid",
		"tgkill",
		"tkill",
		"wait4",
		"waitid",
		"waitpid",
		"pidfd_open",
		"pidfd_send_signal",
		"set_tid_address",
	},
	"Networking Client": {
		"bind",
		"connect",
		"getpeername",
		"getsockname",
		"getsockopt",
		"recv",
		"recvfrom",
		"recvmmsg",
		"recvmmsg_time64",
		"recvmsg",
		"send",
		"sendmmsg",
		"sendmsg",
		"sendto",
		"setsockopt",
		"shutdown",
		"socket",
	},
	"Networking Server": {
		"accept",
		"accept4",
		"bind",
		// "connect",
		"getpeername",
		"getsockname",
		"getsockopt",
		"listen",
		"recvfrom",
		"recvmsg",
		"sendto",
		"setsockopt",
		"shutdown",
		"socket",
	},
	"Local Sockets Client": {
		"socket",
		"connect",
		"shutdown",
	},
	"Basic File Descriptor Operations": {
		"close",
		"close_range",
		"read",   // generic read on any file descriptor (files, sockets, pipes)
		"readv",  // vectored read on any file descriptor
		"write",  // generic write on any file descriptor (files, sockets, pipes)
		"writev", // vectored write on any file descriptor
	},
	"File Descriptor Operations": {
		"dup",           // duplicate an existing file descriptor
		"dup2",          // duplicate an existing file descriptor
		"dup3",          // duplicate an existing file descriptor
		"epoll_create",  // create an epoll file descriptor
		"epoll_create1", // create a new instance of an epoll set for monitoring file descriptors
		"epoll_ctl",     // program the event filter for an epoll instance
		"epoll_pwait",   // wait for an I/O event on an epoll filedescriptor with the option for user-space signal masking
		"epoll_pwait2",  // wait for an I/O event on an epoll file descriptor with optional behavior for handling signals
		"epoll_wait",    // waits for an I/O event on an epoll file descriptor
		"eventfd",       // used to create a file descriptor for event notification
		"eventfd2",      // creates an "eventfd" object that can be used as an event wait/notify mechanism by user-space applications, and by the kernel to notify user-space applications of events
		"fcntl",         // change the filedescriptor
		"poll",          // waits for one of a set of file descriptors to become ready to perform I/O operations.
		"ppoll",         // poll file descriptors with a timeout given with nanosecond precision
		"ppoll_time64",  // used to poll the given file descriptor sets with the given timeout value in a Linux-based system
		"pselect6",      // used to select or monitor many files or sockets for readability, writability, prior-to-termination conditions etc
		"select",        // Wait for some event on a group of files or sockets
		"signalfd",      // creates a file descriptor that can be used to accept signals
		"signalfd4",     // - create a file descriptor to receive signals
		"pipe",
		"pipe2",
	},
	"Memory Management": {
		"brk",
		"madvise",
		"map_shadow_stack",
		"memfd_create",
		"memfd_secret",
		"mincore",
		"mlock",
		"mlock2",
		"mlockall",
		"mmap",
		"mprotect",
		"mremap",
		"msync",
		"munlock",
		"munlockall",
		"munmap",
		"remap_file_pages",
		"pkey_alloc",
		"pkey_free",
		"pkey_mprotect",
	},
	"Signals": {
		"rt_sigaction",
		"rt_sigpending",
		"rt_sigprocmask",
		"rt_sigqueueinfo",
		"rt_sigreturn",
		"rt_sigsuspend",
		"rt_sigtimedwait",
		"rt_sigtimedwait_time64",
		"rt_tgsigqueueinfo",
		"sigaltstack",
		"sigprocmask",
		"sigreturn",
	},
	"Timers and Clocks": {
		"adjtimex",
		"alarm",
		"clock_adjtime",
		"clock_getres",
		"clock_gettime",
		"clock_nanosleep",
		"getitimer",
		"gettimeofday",
		"setitimer",
		"time",
		"timer_create",
		"timer_delete",
		"timer_getoverrun",
		"timer_gettime",
		"timer_settime",
		"timerfd_create",
		"timerfd_gettime",
		"timerfd_settime",
		"times",
	},
	"Security and Permissions": {
		"chdir",
		"capget",
		"capset",
		"setxattr",
		"fsetxattr",
		"lsetxattr",
		"lremovexattr",
		"removexattr",
		"fremovexattr",
		"setuid",
		"setgid",
		"seteuid",
		"setegid",
		"setresuid",
		"setresgid",
		"setfsuid",
		"setfsgid",
		"setgroups",
		"getuid",
		"getgid",
		"geteuid",
		"getegid",
		"getgroups",
		"seccomp",
	},
	"System Information": {
		// "getcpu",
		"uname",
		"sysinfo",
		"getrlimit",
		"getrusage",
		"setrlimit",
		"ugetrlimit",
	},
	"IPC": {
		"semctl",
		"semget",
		"semop",
		"semtimedop",
		"shmat",
		"shmctl",
		"shmdt",
		"shmget",
		"socketpair",
		"msgctl",
		"msgget",
		"msgrcv",
		"msgsnd",
		"mq_getsetattr",
		"mq_notify",
		"mq_open",
		"mq_timedreceive",
		"mq_timedsend",
		"mq_unlink",
	},
	"Synchronization": {
		"futex",
		"futex_wait",
		"futex_wake",
		"set_robust_list",
		"get_robust_list",
		"flock",
	},
	"Miscellaneous": {
		"landlock_add_rule",
		"landlock_create_ruleset",
		"landlock_restrict_self",
		"sync",
		"syncfs",
		"tee",
		"splice",
		"vmsplice",
		"process_mrelease",
		"rseq",
		"membarrier",
		"restart_syscall",
		"cachestat",
		"getrandom",
		"io_cancel",
		"ioctl",
		"io_destroy",
		"io_getevents",
		"ioprio_get",
		"ioprio_set",
		"io_setup",
		"io_submit",
		"prlimit64",
	},
}
